FROM node:22-bookworm

WORKDIR /app

ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"

RUN corepack enable && corepack prepare pnpm@9.14.4 --activate

COPY . .

RUN pnpm install

EXPOSE 5173

CMD ["bash", "-lc", "pnpm migrations migrate && pnpm dev --host 0.0.0.0 --port 5173"]